title: "TechbyRuss"
description: "Network engineering, cybersecurity, homelab and automation projects."
url: "https://tangoman222.github.io"
baseurl: ""
theme: null
markdown: kramdown
permalink: /blog/:title/

collections:
  projects:
    output: true
    permalink: /projects/:name/
